# Generated by Django 5.2.4 on 2025-07-29 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
