# Generated by Django 5.2.4 on 2025-08-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_tag_course_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tag',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
