# Generated by Django 5.2.4 on 2025-08-02 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['order']},
        ),
    ]
