# Generated by Django 5.2.4 on 2025-08-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_section_options_alter_video_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='order2',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
