# Generated by Django 5.2.4 on 2025-08-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_video_order2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='order2',
        ),
    ]
